version: '3'

services:
  backend:
    build: 
      context: ./backend
    env_file: ./backend/.env
    ports:
      - "5000:3000" # Map the backend port
    volumes:
      - ./backend:/app
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000" # Map the frontend port
    volumes:
      - ./frontend:/app

